var data={
    weblist:[
        {
            year: 2019,
            name: "心蜜 Xinmi",
            subname: "Xinmi",
            url: "http://demoweb.byethost10.com/xinmi/tw/index.html",
            url_text: "Xinmi.com",
            description: "心蜜陪一顆心長大。負責網頁視覺設計與前端開發",
            rwd: true,
            development: true,
            design: true,
            designtype: "Design",
            img_thumbs: "xinmi.jpg",
            img_default: "xinmi-banner",
            demo: ["xinmi.jpg"]
        },
        {

            year: 2018,
            name: "夏普中國官網",
            subname: "Sharp of China",
            url: "http://demoweb.byethost10.com/sharp",
            url_text: "sharp.com",
            description: "夏普中國官網，負責網頁HTML。",
            rwd: true,
            development: true,
            design: false,
            designtype: "Design",
            img_thumbs: "sharp.jpg",
            img_default: "sharp-banner",
            demo: ["sharp.jpg"]
        },
        {

            year: 2017,
            name: "DFMS System",
            subname: "DFMS",
            url: "",
            url_text: "",
            description: "DFMS為一個工單管理系統，負責整體視覺設計。",
            rwd: false,
            development: false,
            design: true,
            designtype: "Design",
            img_thumbs: "dfms.jpg",
            img_default: "dfms-banner",
            demo: ["dfms_1.jpg","dfms_2.jpg","dfms_3.jpg","dfms_4.jpg"]
        },
        {
            year: 2017,
            name: "福利講堂::英文線上學習平台",
            subname: "Fuli Forum",
            url: "https://www.fuli-forum.com.tw/",
            url_text: "www.fuli-forum.com.tw",
            description: "菁英國際所屬之福利講堂(Fuli Forum)。團隊致力於開發線上課程及多元化的教學環境，希望有學習需求者能透過數位學習的方式達到有效的學習效果。",
            rwd: true,
            development: true,
            design: true,
            designtype: "Design",
            img_thumbs: "fuli.jpg",
            img_default: "fuli-banner",
            demo: ["fuli-1.jpg","fuli-2.jpg","fuli-3.jpg","fuli-4.jpg","fuli-5.jpg"]
        },
        {
            year: 2017,
            name: "夏普社區",
            subname: "SHARP Forum",
            url: "",
            url_text: "",
            description: "使用Discuz社區開放軟體架設論壇，負責整體視覺設計，並將設計畫面落實於Discuz版面上。",
            rwd: true,
            development: true,
            design: true,
            designtype: "Design",
            img_thumbs: "sharp.jpg",
            img_default: "sharp-banner",
            demo: ["sharp_1.jpg","sharp_2.jpg","sharp_3.jpg","sharp_4.jpg"]
        },
        // {
        //     year: 2017,
        //     name: "永盛豐企業有限公司::門的專家",
        //     subname: "YCF",
        //     url: "http://www.reliable-ycf.com.tw/",
        //     url_text: "www.reliable-ycf.com.tw",
        //     description: "永盛豐企業有限公司主要經銷防火門、玄關門，產品適用於各式裝修案場、集合式住宅、商辦大樓等。團隊成員於門的產業平均有10年以上的資歷，針對大小案件從規劃設計、製造、安裝施工到維修服務皆全程參與，提供最專業完善的服務。",
        //     rwd: true,
        //     development: true,
        //     design: true,
        //     designtype: "Design",
        //     img_thumbs: "ycf.jpg",
        //     img_default: "ycf-banner",
        //     demo: ["ycf-1.jpg","ycf-2.jpg"]
        // },
        {
            year: 2017,
            name: "幫我修",
            subname: "Help me repair it!",
            url: "#",
            url_text: "設計規劃提案",
            description: "在線定價 · 公開透明  ★  專業認證 · 品牌授權  ★  一鍵上門 · 守時高效",
            rwd: false,
            development: false,
            design: true,
            designtype: "Design",
            img_thumbs: "repair.jpg",
            img_default: "repair-banner",
            demo: ["repair-1.jpg","repair-2.jpg","repair-3.jpg","repair-4.jpg"]
        },
        {
            year: 2017,
            name: "Coil漫畫社群",
            subname: "Coil",
            url: "https://www.coilplanet.net",
            url_text: "www.coilplanet.net",
            description: "以APP黃、黑色為主視覺，現代簡潔大方的調性，呈現活潑與朝氣。",
            rwd: true,
            development: true,
            design: true,
            designtype: "Design",
            img_thumbs: "coil.jpg",
            img_default: "coil-banner",
            demo: ["coil-1.jpg","coil-2.jpg","coil-3.jpg"]
        },
        // {
        //     year: 2017,
        //     name: "豪山廚具購物網",
        //     subname: "Kitchenware Shopping",
        //     url: "http://woodstonedemo.byethost24.com/kitchen",
        //     url_text: "Demo：http://woodstonedemo.byethost24.com/kitchen",
        //     description: "【現代簡約】廚房是家人聯繫情感的地方，更是展現生活品味的的場所。以壁紙、大理石紋理為背景營造廚房氛圍，廚房全景搭配影片展示，彷彿置身其中做料理。逐步陳列每ㄧ項廚具，美味料理需要好的廚具，讓購物者挑起烹飪衝動與購買動機。豪山廚具是您的廚房好夥伴!",
        //     rwd: true,
        //     development: true,
        //     design: true,
        //     designtype: "Design",
        //     img_thumbs: "kitchen.jpg",
        //     img_default: "kitchen-banner",
        //     demo: ["kitchen-1.jpg","kitchen-2.jpg","kitchen-3.jpg","kitchen-4.jpg","kitchen-5.jpg"]
        // },
        // {
        //     year: 2017,
        //     name: "康活保養品購物網",
        //     subname: "Kof Beauty",
        //      url: "http://woodstonedemo.byethost24.com/kof",
        //     url_text: "Demo：http://woodstonedemo.byethost24.com/kof",
        //     description: "【保養。女。花朵】以花、粉彩風格凸顯女性溫柔。象徵勤於保養女人也能向花一樣美麗綻放。",
        //     rwd: true,
        //     development: true,
        //     design: true,
        //     designtype: "Design",
        //     img_thumbs: "beauty.jpg",
        //     img_default: "beauty-banner",
        //     demo: ["beauty-1.jpg","beauty-2.jpg","beauty-3.jpg","beauty-4.jpg","beauty-5.jpg"]
        // },
        // {
        //     year: 2016,
        //     name: "毛小孩鮮食網",
        //     subname: "Pet Food Shopping",
        //     url: "#",
        //     url_text: "設計提案",
        //     description: "毛小孩鮮食網，以紅、黃、藍三大色塊強調鮮食選單區，以大篇幅圖片吸引目光，提高購物。",
        //     rwd: false,
        //     development: false,
        //     design: true,
        //     designtype: "Design",
        //     img_thumbs: "pet.jpg",
        //     img_default: "pet-banner",
        //     demo: ["pet-1.jpg","pet-2.jpg"]
        // },
        // {
        //     year: 2016,
        //     name: "幸福苗栗三部曲",
        //     subname: "Happiness Miaoli",
        //     url: "#",
        //     url_text: "設計提案",
        //     description: "以桐花白、黃、粉紅三色為網頁主視覺，黃色簡潔明快，粉紅代表幸福，一致色彩，營造幸福苗栗的氛圍，以大篇幅圖片吸引目光。",
        //     rwd: false,
        //     development: false,
        //     design: true,
        //     designtype: "Design",
        //     img_thumbs: "happiness_miaoli.jpg",
        //     img_default: "happiness_miaoli-banner",
        //     demo: ["happiness_miaoli-1.jpg","happiness_miaoli-2.jpg","happiness_miaoli-3.jpg","happiness_miaoli-4.jpg"]
        // },
        {
            year: 2016,
            name: "雲列印",
            subname: "Easy Printing.",
            url: "#",
            url_text: "設計提案",
            description: "雲列印 Easy Printing.",
            rwd: false,
            development: false,
            design: true,
            designtype: "Design",
            img_thumbs: "printing.jpg",
            img_default: "printing-banner",
            demo: ["printing-1.jpg","printing-2.jpg"]
        },
        {
            year: 2016,
            name: "雲智慧Maxnerva",
            subname: "Maxnerva Website",
            url: "http://www.maxnerva.com/",
            url_text: "www.maxnerva.com",
            description: "雲智慧為一家科技公司，以藍色帶出專業科技感，傳遞專業與科技服務理念。",
            rwd: true,
            development: true,
            design: true,
            designtype: "Co-Design",
            img_thumbs: "maxnerva.jpg",
            img_default: "maxnerva-banner",
            demo: ["maxnerva-1.jpg","maxnerva-2.jpg"]
        },
        {
            year: 2016,
            name: "寶貝來交朋友",
            subname: "https://bbcomes.com/inviteFriends",
            url: "https://bbcomes.com/inviteFriends",
            url_text: "inviteFriends",
            description: "寶貝來了解新世代父母親的焦慮與無助，我們期望能和新世代的父母一起用最剛好的溫度丶最適宜的態度，以及育兒專家丶醫護等專業建議，幫助您一同解開小小人兒的成長秘密。",
            rwd: true,
            development: true,
            design: true,
            designtype: "Design",
            img_thumbs: "bbcomesfriends.jpg",
            img_default: "bbcomesfriends-banner",
            demo: ["bbcomesfriends.jpg"]
        },
        // {
        //     year: 2016,
        //     name: "木石設計",
        //     subname: "WoodStone Website",
        //     url: "http://woodstonedesign.github.io",
        //     url_text: "woodstonedesign.github.io",
        //     description: "木石設計提供網頁設計&開發、App流程與介面設計、使用者經驗服務。融入使用者經驗設計思維，提供友善易懂的操作介面，帶給使用者良好的體驗。",
        //     rwd: true,
        //     development: true,
        //     design: true,
        //     designtype: "Design",
        //     img_thumbs: "woodstone.jpg",
        //     img_default: "woodstone-banner",
        //     demo: ["woodstone-1.jpg","woodstone-2.jpg"]
        // },
        {
            year: 2016,
            name: "淨土藝術",
            subname: "Art of Rangniang",
            url: "http://www.rangniang.org",
            url_text: "www.rangniang.org",
            description: "淨土藝術為讓娘寺的官方網站，讓娘寺全名為「讓娘彭措帖慶林」，意謂「讓娘圓滿大乘洲」，位於青海省玉樹州玉樹市以北60公里處。淨土藝術網站以集資為目標，期望透過募資方式重建因地震而倒塌的建築，祈求儘快實現教學樓及餐飲問題，愛心人士的捐助，讓這些弱小的朋友擁有一個教學樓。",
            rwd: true,
            development: true,
            design: true,
            designtype: "Co-Design",
            img_thumbs: "rangniang.jpg",
            img_default: "rangniang-banner",
            demo: ["rangniang-1.jpg"]
        },
        {
            year: 2016,
            name: "北大醫療腦健康",
            subname: "Brain Health",
            url: "http://weixin.pkucarenjk.com",
            url_text: "weixin.pkucarenjk.com",
            description: "北大醫療腦健康為一兒童量表型測驗網站，透過簡單的量表測驗帶你輕鬆認識腦健康。以水彩風格為設計，讓醫療不再是冰冷感受，充滿活潑、童趣、陪伴的體驗。",
            rwd: true,
            development: true,
            design: false,
            img_thumbs: "brainhealth.jpg",
            img_default: "brainhealth-banner",
            demo: ["brainhealth-1.jpg"]
        },
        {
            year: 2016,
            name: "寶貝來寵愛媽咪好孕福袋",
            subname: "Love mommy,love baby.",
            url: "https://bbcomes.com/mamifun",
            url_text: "bbcomes.com/mamifun",
            description: "寶貝來了解新世代父母親的焦慮與無助，我們期望能和新世代的父母一起用最剛好的溫度丶最適宜的態度，以及育兒專家丶醫護等專業建議，幫助您一同解開小小人兒的成長秘密。",
            rwd: true,
            development: true,
            design: true,
            designtype: "Design",
            img_thumbs: "mamifun.jpg",
            img_default: "mamifun-banner",
            demo: ["mamifun-1.jpg"]
        },
        {
            year: 2015,
            name: "【夏日暖爸季】我家爸爸超級暖",
            subname: "Happy Father's Day!",
            url: "https://bbcomes.com/activity/summerdad",
            url_text: "summerdad",
            description: "全天下辛苦的爸爸們，父親節快樂！你家有個願意陪孩子玩到滿身大汗、氣喘吁吁的爸爸嗎？寶貝來父親節活動網站以「我的爸爸是超人，爸爸願意為你做牛做馬」為設計理念。",
            rwd: true,
            development: true,
            design: true,
            designtype: "Design",
            img_thumbs: "summerdad.jpg",
            img_default: "summerdad-banner",
            demo: ["summerdad-1.jpg"]
        },
        {
            year: 2015,
            name: "寶貝來BBcomes",
            subname: "Hello!Baby.Hello!World.",
            url: "https://bbcomes.com/",
            url_text: "bbcomes.com",
            description: "寶貝來了解新世代父母親的焦慮與無助，我們期望能和新世代的父母一起用最剛好的溫度丶最適宜的態度，以及育兒專家丶醫護等專業建議，幫助您一同解開小小人兒的成長秘密。",
            rwd: true,
            development: true,
            design: true,
            designtype: "Co-Design",
            img_thumbs: "bbcomes.jpg",
            img_default: "bbcomes-banner",
            demo: ["bbcomes-1.jpg"]
        },
        {
            year: 2015,
            name: "手滑漫畫",
            subname: "TapTapComic",
            url: "",
            url_text: "",
            description: "玩漫畫。看漫畫。盡在手滑漫畫。此為手滑漫畫App的推廣網頁，以漫畫風格介紹行銷app。",
            rwd: true,
            development: true,
            design: true,
            designtype: "Design",
            img_thumbs: "taptapcomic.jpg",
            img_default: "taptapcomic-banner",
            demo: ["taptapcomic-1.png","taptapcomic-2.jpg"]
        },
        // {
        //     year: 2015,
        //     name: "陽朔旅遊網",
        //     subname: "Travel around Yangshuo.",
        //     url: "#",
        //     url_text: "設計提案",
        //     description: "旅遊網網頁設計提案",
        //     rwd: false,
        //     development: false,
        //     design: true,
        //     designtype: "Design",
        //     img_thumbs: "yangshuo.jpg",
        //     img_default: "yangshuo-banner",
        //     demo: ["yangshuo-1.png"]
        // },
        // {
        //     year: 2014,
        //     name: "和熹生活",
        //     subname: "The Life of Hexi.",
        //     url: "#",
        //     url_text: "網頁開發",
        //     description: "和熹生活為一個老年人社群網站，專注於分享健康知識、大小活動與個人健康管理。以企業代表色-紅色為設計，傳遞熱情、活躍，期許能有安享幸福晚年的生活。",
        //     rwd: false,
        //     development: true,
        //     design: false,
        //     img_thumbs: "hexi.jpg",
        //     img_default: "hexi-banner",
        //     demo: ["hexi-1.jpg"]
        // },
        {
            year: 2014,
            name: "DoEZ",
            subname: "EZ Chat.EZ Talk.",
            url: "",
            url_text: "網頁開發",
            description: "都易[Do-EZ]是您生活上最麻吉的好幫手，我們把大家最常用的免費即時通訊，結合了生活上的邀約與邀請，可以讓您一邊聊天，一邊把聊天記錄迅速建立起來成為一個提醒事項，或把聊天內容傳送給對方，邀請對方加入這個活動。",
            rwd: false,
            development: true,
            design: false,
            img_thumbs: "doez.jpg",
            img_default: "doez-banner",
            demo: ["doez-1.jpg"]
        },
        {
            year: 2014,
            name: "追跡者",
            subname: "EZ Chat.EZ Talk.",
            url: "",
            url_text: "",
            description: "安全，簡單，追跡。追跡者，您的安全運輸專家。",
            rwd: false,
            development: true,
            design: true,
            designtype: "Design",
            img_thumbs: "tracking.jpg",
            img_default: "tracking-banner",
            demo: ["tracking-1.jpg"]
        },
        {
            year: 2014,
            name: "eHR 登入",
            subname: "Register & Login",
            url: "",
            url_text: "設計",
            description: "系統後台登入頁。",
            rwd: false,
            development: true,
            design: true,
            designtype: "Design",
            img_thumbs: "eHR.jpg",
            img_default: "eHR-banner",
            demo: ["eHR-1.png","eHR-2.jpg"]
        },
        {
            year: 2014,
            name: "WISE Lab",
            subname: "Wireless Innovative System EM-Applied",
            url: "http://wisbal.ee.ncku.edu.tw",
            url_text: "wisbal.ee.ncku.edu.tw",
            description: "國立成功大學電機系無線創新系統電磁應用實驗室(WISE Lab)網站。",
            rwd: true,
            development: true,
            design: true,
            designtype: "Design",
            img_thumbs: "wiselab.jpg",
            img_default: "wiselab-banner",
            demo: ["wiselab-1.jpg","wiselab-2.jpg"]
        }
        
    ],
    applist:[
        {
            year: 2018,
            name: "ScanGo 掃碼購",
            subname: "Wechat UI",
            description: "掃碼購為一個微信小程序，使用於智慧門店中掃碼購物結帳。負責UI視覺設計與App icon設計。",
            android: true,
            ios: true,
            design: true,
            img_thumbs: "ScanGo.jpg",
            img_default: "ScanGo-banner",
            demo: ["ScanGo_cover.jpg","ScanGo01.jpg","ScanGo02.jpg"]
        },
        {
            year: 2018,
            name: "富店通",
            subname: "Shop Management",
            description: "富店通為店長管理門店APP，銷售分析、門店、訂單會員管理與銷售員排班簽到一應俱全。負責UI視覺設計與切圖。",
            android: true,
            ios: true,
            design: true,
            img_thumbs: "shop.gif",
            img_default: "shop-banner",
            demo: ["shop_cover.gif","shop01.jpg","shop02.jpg"]
        },
        {
            year: 2018,
            name: "世足大競猜",
            subname: "WorldCup",
            description: "2018世足大賽期間電商平台推出世足大競猜活動，使用微信參與活動，猜猜冠軍/亞軍/季軍球隊。主要負責UI視覺設計。",
            android: true,
            ios: true,
            design: true,
            img_thumbs: "worldcup.jpg",
            img_default: "worldcup-banner",
            demo: ["worldcup_cover.jpg","worldcup01.jpg"]
        },
        {
            year: 2017,
            name: "HR 考勤",
            subname: "Leave Attendance Management",
            url: "https://marvelapp.com/6151f7h/screen/30362255",
            url_text: "HR Prototype",
            description: "HR考勤管理，簽到、申請單、查詢功能一應俱全。負責UI流程規劃、視覺設計到App icon，Android與iOS切圖。",
            android: true,
            ios: true,
            design: true,
            img_thumbs: "hr.jpg",
            img_default: "hr-banner",
            demo: ["hr_app-1.jpg","hr_app-2.png"]
        },
        {
            year: 2017,
            name: "Car Insurance Services",
            subname: "Personalized Services",
            description: "個人化汽車保險服務，客戶亦可自由添加額外保障。",
            android: true,
            ios: true,
            design: true,
            img_thumbs: "carinsurance.jpg",
            img_default: "carinsurance-banner",
            demo: ["carinsurance-1.jpg","carinsurance-2.jpg","carinsurance-3.jpg"]
        },
        // {
        //     year: 2016,
        //     name: "SAMENU",
        //     subname: "EZ Order.EZ Track.",
        //     url: " https://play.google.com/store/apps/details?id=com.vector.samenu",
        //     url_text: "GooglePlay",
        //     description: "為幫助顧客減少訂餐、等待餐點時間，SAMENU提供顧客與店家雙向服務，app囊括多家商店，提供顧客快速訂、取餐服務，隨時查看目前叫號狀態。店家可透過app管理訂單進度，讓顧客享有便利與快速的購餐服務。*負責UI設計，不含流程與App icon設計。",
        //     android: true,
        //     ios: true,
        //     design: true,
        //     img_thumbs: "SAMENU.jpg",
        //     img_default: "SAMENU-banner",
        //     demo: ["SAMENU-1.jpg"]
        // },
        {
            year: 2015,
            name: "手滑漫畫",
            subname: "TapTapToon",
            description: "玩漫畫。看漫畫。盡在手滑漫畫。你有許多不吐不快的話嗎?你有滿腦子好笑的話題想要給朋友知道嗎?用單純的文字來表達太落伍了，用漫畫吧，讓你想說的話更生動活潑有趣。",
            android: true,
            ios: true,
            design: true,
            img_thumbs: "TapTapToon.jpg",
            img_default: "taptapcomic-banner",
            demo: ["TapTapToon-1.png"]
        },
        {
            year: 2014,
            name: "活動票卷app",
            subname: "EZ Tickets.",
            description: "便捷、快速取票與驗票app。",
            android: true,
            ios: true,
            design: true,
            img_thumbs: "tickets.jpg",
            img_default: "tickets-banner",
            demo: ["tickets-1.jpg"]
        },
        {
            year: 2014,
            name: "HealthCare-健康管理",
            subname: "Health is wealth.",
            description: "HealthCare為一個自我健康管理app，擁有健康報告、健康管理、運動紀錄、行事曆、健康資訊、預約健檢六大功能。",
            android: true,
            ios: true,
            design: true,
            img_thumbs: "HealthCare.jpg",
            img_default: "HealthCare-banner",
            demo: ["HealthCare-1.jpg","HealthCare-2.png","HealthCare-3.jpg"]
        }
    ],
    uilist:[
        {
            name: "Leaderboard",
            img_default: "day17"
        },
        {
            name: "Profile",
            img_default: "day4"
        },
        {
            name: "Music Player",
            img_default: "day6"
        },
        {
            name: "404 Page",
            img_default: "day8"
        },
        {
            name: "Email check",
            img_default: "day18"
        },
        {
            name: "Sport Chart",
            img_default: "day16"
        },
        {
            name: "Night Mode",
            img_default: "day13"
        },
        {
            name: "Shopping",
            img_default: "day10"
        }
    ]
};



var vm = new Vue({
    el: "#allprojects",
    data: data
});
